"""
Training and Validation Pairwise Dataset Builder.
Combines True Positive links and Hard Negative candidate pairs into feature matrices.
"""

from typing import Any, Dict, List, Optional, Set, Tuple
import numpy as np
import pandas as pd

from .extractor import (
    FEATURE_NAMES,
    extract_pair_features_fast,
    prepare_entity_profile,
)


def build_pairwise_dataset(
    s1_df: pd.DataFrame,
    s2_df: pd.DataFrame,
    s3_df: pd.DataFrame,
    candidate_dict: Dict[str, Set[str]],
    ground_truth_dict: Optional[Dict[str, Set[str]]] = None,
    include_all_true_positives: bool = True,
) -> Tuple[pd.DataFrame, np.ndarray, pd.DataFrame]:
    """
    High-speed, memory-efficient pairwise dataset builder.
    Pre-computes entity profiles and uses fast RapidFuzz feature extraction.
    """
    # 1. Pre-compute S1 profiles
    s1_profiles: Dict[str, Dict[str, Any]] = {}
    for eid, name, addr in zip(s1_df["entity_id"].values, s1_df["business_name"].values, s1_df["business_address"].values):
        s1_profiles[str(eid)] = prepare_entity_profile(str(name), str(addr))

    # 2. Collect only target IDs that appear in candidates or ground truth
    all_needed_targets = set()
    for s1_id, cand_set in candidate_dict.items():
        all_needed_targets.update(cand_set)
        if include_all_true_positives and ground_truth_dict:
            all_needed_targets.update(ground_truth_dict.get(s1_id, set()))

    # 3. Pre-compute Target profiles only for needed targets
    target_profiles: Dict[str, Dict[str, Any]] = {}
    
    # Filter S2
    s2_mask = s2_df["entity_id"].isin(all_needed_targets)
    for eid, name, addr in zip(s2_df.loc[s2_mask, "entity_id"].values, s2_df.loc[s2_mask, "business_name"].values, s2_df.loc[s2_mask, "business_address"].values):
        target_profiles[str(eid)] = prepare_entity_profile(str(name), str(addr))

    # Filter S3
    s3_mask = s3_df["entity_id"].isin(all_needed_targets)
    for eid, name, addr in zip(s3_df.loc[s3_mask, "entity_id"].values, s3_df.loc[s3_mask, "business_name"].values, s3_df.loc[s3_mask, "business_address"].values):
        target_profiles[str(eid)] = prepare_entity_profile(str(name), str(addr))

    feature_rows = []
    labels: List[int] = []
    s1_meta: List[str] = []
    target_meta: List[str] = []
    comp_meta: List[float] = []

    for s1_id, cand_set in candidate_dict.items():
        p1 = s1_profiles.get(s1_id)
        if not p1:
            continue

        true_set = ground_truth_dict.get(s1_id, set()) if ground_truth_dict else set()
        
        # Include all candidate pairs generated by blocker
        evaluated_cands = set(cand_set)

        # Optionally add missing true positives for training
        if include_all_true_positives and ground_truth_dict:
            evaluated_cands.update(true_set)

        for target_id in evaluated_cands:
            p2 = target_profiles.get(target_id)
            if not p2:
                continue

            vector = extract_pair_features_fast(p1, p2, source2_prefix=target_id[:2])
            feature_rows.append(vector)

            is_match = 1 if target_id in true_set else 0
            labels.append(is_match)

            s1_meta.append(s1_id)
            target_meta.append(target_id)
            comp_meta.append(vector[15])  # composite_score is feature index 15

    X = pd.DataFrame(feature_rows, columns=FEATURE_NAMES, dtype=np.float32)
    y = np.array(labels, dtype=np.int32)
    meta_df = pd.DataFrame({
        "source1_entity_id": s1_meta,
        "target_entity_id": target_meta,
        "composite_score": comp_meta,
    })

    return X, y, meta_df

