"""
Training and Validation Pairwise Dataset Builder.
Combines True Positive links and Hard Negative candidate pairs into feature matrices.
"""

from typing import Dict, List, Optional, Set, Tuple
import numpy as np
import pandas as pd

from .extractor import FEATURE_NAMES, extract_pair_features


def build_pairwise_dataset(
    s1_df: pd.DataFrame,
    s2_df: pd.DataFrame,
    s3_df: pd.DataFrame,
    candidate_dict: Dict[str, Set[str]],
    ground_truth_dict: Optional[Dict[str, Set[str]]] = None,
    include_all_true_positives: bool = True,
) -> Tuple[pd.DataFrame, np.ndarray, pd.DataFrame]:
    """
    Constructs pairwise feature DataFrame X, binary label array y, and pair metadata DataFrame.
    """
    # Build fast lookup dictionaries
    s1_dict = s1_df.set_index("entity_id").to_dict(orient="index")
    s2_dict = s2_df.set_index("entity_id").to_dict(orient="index")
    s3_dict = s3_df.set_index("entity_id").to_dict(orient="index")

    def get_target_record(eid: str) -> Dict[str, str]:
        if eid.startswith("S2-"):
            return s2_dict.get(eid, {})
        elif eid.startswith("S3-"):
            return s3_dict.get(eid, {})
        return s1_dict.get(eid, {})

    feature_rows = []
    labels = []
    meta_rows = []

    for s1_id, cand_set in candidate_dict.items():
        s1 = s1_dict.get(s1_id)
        if not s1:
            continue

        true_set = ground_truth_dict.get(s1_id, set()) if ground_truth_dict else set()
        
        # Include all candidate pairs generated by blocker
        evaluated_cands = set(cand_set)

        # Optionally add missing true positives for training
        if include_all_true_positives and ground_truth_dict:
            evaluated_cands.update(true_set)

        for target_id in evaluated_cands:
            target_rec = get_target_record(target_id)
            if not target_rec:
                continue

            feat = extract_pair_features(
                name1=s1["business_name"],
                addr1=s1["business_address"],
                country1=s1["country"],
                name2=target_rec.get("business_name", ""),
                addr2=target_rec.get("business_address", ""),
                country2=target_rec.get("country", ""),
                source2_prefix=target_id[:2],
            )

            # Filter to pure feature vector
            vector = [feat[fname] for fname in FEATURE_NAMES]
            feature_rows.append(vector)

            # Label: 1 if true match, 0 if negative candidate
            is_match = 1 if target_id in true_set else 0
            labels.append(is_match)

            meta_rows.append({
                "source1_entity_id": s1_id,
                "target_entity_id": target_id,
                "composite_score": feat["composite_score"],
            })

    X = pd.DataFrame(feature_rows, columns=FEATURE_NAMES)
    y = np.array(labels, dtype=int)
    meta_df = pd.DataFrame(meta_rows)

    return X, y, meta_df
